### ISSUE TITLE
update confussing

### ISSUE THREAD

**Issue by Infernogd** [MetaGG2/NoShake#1]
hi idk if I'm looking at the wrong place but I can't find no global setting
![image](https://github.com/MetaGG2/NoShake/assets/164727301/37f99abc-8893-475a-9a42-37f480179168)
and it was better before but idk Im doing somethin wrong

**Comment by MetaGG2** [comment]
that is the wrong place its in the noshake mod settings sorry if description was a bit confusing
![image](https://github.com/MetaGG2/NoShake/assets/66139777/99e14e97-ebd3-4d14-9c2f-8fa8ce9167a7)
![image](https://github.com/MetaGG2/NoShake/assets/66139777/17a957f8-cc4a-4109-8859-3642a50cc5b0)
![image](https://github.com/MetaGG2/NoShake/assets/66139777/524d410b-2727-47e2-9f7b-1619f236d9ad)

**Comment by InfernoZv** [comment]
oh thats werid cuz when I had it enabled it doesn't work for me but with the old version it does

**Comment by MetaGG2** [comment]
im releasing a fix right now

**Comment by InfernoZv** [comment]
ok thanks

**Comment by InfernoZv** [comment]
did you find out the issue?

**Comment by MetaGG2** [comment]
yes i published a release on github but manual approval is required for my mod to be updated on the geode index

**Comment by InfernoZv** [comment]
hm werid even with the update it doesn't work I will just wait til it gets the update on geode but for now i'm going to use the first version

**Comment by MetaGG2** [comment]
turns out that i built it wrong so ill have to yet again publish another release :|

**Comment by InfernoZv** [comment]
Ah ok now it works for me
