### ISSUE TITLE
Are You Planning To Update This Mod To 2.206?

### ISSUE THREAD

**Issue by Infernogd** [MetaGG2/NoShake#2]
just asking

**Comment by MetaGG2** [comment]
there's no reason to update the mod to 2.206 because disabling shake is in the default settings under the "Visual" tab
![thing](https://github.com/user-attachments/assets/7962a483-3f3c-4d2d-9751-ad73e8699329)

**Comment by InfernoZv** [comment]
Oh whoops I didn’t see this thanks for clarifying
